version: '3.9'

services:
  front:
    image: nextjs-docker
    restart: always
    environment:
      API_HOST: backend
    ports:
      - 80:3000

  backend:
    image: backend-flask:1.0.4
    restart: always
    environment:
      DB_HOST: db
      DB_USER: exampleuser
      DB_PASSWORD: examplepass
    ports:
      - 5000:5000

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./dbdata:/var/lib/mysql
