version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./data/:/var/lib/mysql/
    #     - ./pgdata/:/var/lib/postgresql/data/
    #     - ./init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
