version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres_13
    volumes:
        - ./pgdata/:/var/lib/postgresql/data/
        - ./init/:/docker-entrypoint-initdb.d/
    environment:
      # - POSTGRES_DB=innovds
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
