version: '3.8'
services:
  mysql:
    image: mongo
    container_name: mongo
    # volumes:
    #     - ./pgdata/:/var/lib/postgresql/data/
    #     - ./init/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
